spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/traineeshipdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: trainee_app
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
